/*
 * This file was automatically generated by EvoSuite
 * Sat Feb 14 12:30:58 GMT 2026
 */

package org.example.evosuite;
import org.example.DateUtils;
import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DateUtils_ESTest extends DateUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(9, 21);
      assertEquals("Autumn", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(7, 7);
      assertEquals("Summer", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(6, 25);
      assertEquals("Summer", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(4, 4);
      assertEquals("Spring", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(3, 22);
      assertEquals("Spring", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(12, 21);
      assertEquals("Winter", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(1, 31);
      assertEquals("Winter", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(9, 24);
      assertEquals("Autumn", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(9, 9);
      assertEquals("Summer", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(8, 8);
      assertEquals("Summer", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(6, 6);
      assertEquals("Spring", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(6, 21);
      assertEquals("Summer", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(3, 3);
      assertEquals("Winter", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(3, 21);
      assertEquals("Spring", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(2, 6);
      assertEquals("Winter", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(12, 29);
      assertEquals("Winter", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(12, 12);
      assertEquals("Autumn", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(9, 1509);
      assertEquals("Invalid", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(3, (-1254));
      assertEquals("Invalid", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(21, 21);
      assertEquals("Invalid", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason(5, 5);
      assertEquals("Spring", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      String string0 = dateUtils0.getSeason((-1367), (-1367));
      assertEquals("Invalid", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      boolean boolean0 = dateUtils0.isLeapYear(12);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      boolean boolean0 = dateUtils0.isLeapYear(6);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      boolean boolean0 = dateUtils0.isLeapYear((-711));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      DateUtils dateUtils0 = new DateUtils();
      boolean boolean0 = dateUtils0.isLeapYear(0);
      assertTrue(boolean0);
  }
}
